name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'  # or the version you need

      - name: Install Composer dependencies
        run: composer install --no-dev --no-progress --no-suggest --prefer-dist

      - name: Copy .env.example to .env
        run: cp .env.example .env

      - name: Set environment variables
        run: |
          echo "APP_ENV=production" >> .env
          echo "APP_DEBUG=false" >> .env
          echo "APP_URL=https://jolly-mud-03bd67400.5.azurestaticapps.net" >> .env

      - name: Generate application key
        run: php artisan key:generate

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'  # or the version you need

      - name: Build front-end assets
        run: |
          npm install
          npm run production

      - name: Optimize configuration
        run: php artisan config:cache

      - name: Set up environment variables
        run: php artisan config:cache

      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_JOLLY_MUD_03BD67400 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "." # Root of the Laravel app
          api_location: "" # No separate API location
          output_location: "public" # Public directory for deployment

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_JOLLY_MUD_03BD67400 }}
          action: "close"
